class AppConstants {
  static const String appName = 'Farm Solution';
  static const String appTagline = 'Complete farming Solution';
  static const String shopName = 'Sonpur Sewa Samiti (सोनपुर सेवा समिति)';
  static const String shopPhone = '8269202960';
  static const String shopPhoneFormatted = '+91 82692 02960';
  static const String shopWhatsAppUrl = 'https://wa.me/918269202960';
  static const String shopCallUrl = 'tel:8269202960';
  static const String shopAddressEn = 'Near UP Gramin Bank, Jethwara, Pratapgarh, Uttar Pradesh 230129';
  static const String shopAddressHi = 'यूपी ग्रामीण बैंक के पास, जेठवारा, प्रतापगढ़, उत्तर प्रदेश 230129';

  // Seed Crops
  static final List<Map<String, dynamic>> initialCrops = [
    {
      'id': 'crop_001',
      'nameEn': 'Wheat (HD-2967)',
      'nameHi': 'गेहूं (एच.डी. 2967)',
      'variety': 'HD-2967 High Yielding',
      'fieldSize': 2.5,
      'fieldUnit': 'Acre',
      'sowingDate': DateTime.now().subtract(const Duration(days: 35)).toIso8601String(),
      'expectedHarvestDate': DateTime.now().add(const Duration(days: 85)).toIso8601String(),
      'currentStageEn': 'Tillering & Vegetative Growth',
      'currentStageHi': 'कल्ले फूटना एवं वानस्पतिक वृद्धि',
      'progress': 0.35,
      'healthStatus': 'healthy',
      'tasks': [
        {
          'id': 'task_1',
          'titleEn': 'First Top Dressing of Shriram Urea (45 kg)',
          'titleHi': 'श्रीराम यूरिया का पहला टॉप ड्रेसिंग (45 कि.ग्रा.)',
          'descriptionEn': 'Broadcast urea before light evening irrigation.',
          'descriptionHi': 'हल्की सिंचाई से पहले यूरिया का समान छिड़काव करें।',
          'dueDate': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
          'isCompleted': true,
          'category': 'fertilizer',
        },
        {
          'id': 'task_2',
          'titleEn': 'Apply Shriram Ziva Root Energizer (4 kg/Acre)',
          'titleHi': 'श्रीराम जीवा जड़ पोषक (4 किग्रा/एकड़) डालें',
          'descriptionEn': 'Mix with soil or urea to promote active tiller branching.',
          'descriptionHi': 'मिट्टी या यूरिया के साथ मिलाकर जड़ों के तीव्र विकास हेतु डालें।',
          'dueDate': DateTime.now().add(const Duration(days: 5)).toIso8601String(),
          'isCompleted': false,
          'category': 'fertilizer',
        },
      ],
      'notes': 'Sown after Paddy harvest. Soil test showed good response to Shriram Ziva.',
    },
    {
      'id': 'crop_002',
      'nameEn': 'Mustard (Pusa Jai Kisan)',
      'nameHi': 'सरसों (पूसा जय किसान)',
      'variety': 'Bio-902 / Pusa Jai Kisan',
      'fieldSize': 1.5,
      'fieldUnit': 'Acre',
      'sowingDate': DateTime.now().subtract(const Duration(days: 55)).toIso8601String(),
      'expectedHarvestDate': DateTime.now().add(const Duration(days: 40)).toIso8601String(),
      'currentStageEn': 'Pod Formation & Siliqua Filling',
      'currentStageHi': 'फलियां बनना एवं दाना भराव',
      'progress': 0.65,
      'healthStatus': 'warning',
      'tasks': [
        {
          'id': 'task_m1',
          'titleEn': 'Aphid Monitoring with Shriram Mahun Nashak',
          'titleHi': 'माहू कीट नियंत्रण हेतु श्रीराम माहू नाशक का छिड़काव',
          'descriptionEn': 'Spray 100ml in 200L water per 1 Acre.',
          'descriptionHi': '100 मिली 200 लीटर पानी में प्रति एकड़ छिड़कें।',
          'dueDate': DateTime.now().add(const Duration(days: 1)).toIso8601String(),
          'isCompleted': false,
          'category': 'pesticide',
        },
      ],
      'notes': 'Good branching observed. Watch for morning aphid clustering.',
    },
  ];

  // Seed AI Scans with Shriram Fertilizers & Chemicals mapping
  static final List<Map<String, dynamic>> initialScans = [
    {
      'id': 'scan_101',
      'cropNameEn': 'Wheat Leaf (Triticum aestivum)',
      'cropNameHi': 'गेहूं की पत्ती (Wheat)',
      'diseaseNameEn': 'Yellow Rust (Puccinia striiformis)',
      'diseaseNameHi': 'पीला रतुआ (येलो रस्ट)',
      'confidenceScore': 0.96,
      'isHealthy': false,
      'symptomsEn': 'Yellow/orange powdery pustules arranged in parallel linear stripes along leaf veins.',
      'symptomsHi': 'पत्तियों की शिराओं पर पीले-नारंगी रंग की धारियों के रूप में फफोले दिखना।',
      'chemicalRemedyEn': 'Shriram Suraksha (Hexaconazole 5% SC): Spray @ 400 ml in 200 Liters of water per 1 Acre.',
      'chemicalRemedyHi': 'श्रीराम सुरक्षा (हेक्साकोनाजोल 5% एससी): 400 मिली 200 लीटर पानी में मिलाकर प्रति 1 एकड़ छिड़कें।',
      'organicRemedyEn': 'Foliar spray of 10% Cow Urine + Neem Seed Kernel Extract (5%).',
      'organicRemedyHi': '10% गोमूत्र और 5% नीम निबोली अर्क का घोल बनाकर पर्णीय छिड़काव करें।',
      'preventionEn': 'Avoid excess nitrogen fertilizer, use rust-resistant certified seeds (HD-3086).',
      'preventionHi': 'अत्यधिक यूरिया के उपयोग से बचें तथा रोगरोधी प्रमाणित बीजों का चयन करें।',
      'scanDate': DateTime.now().subtract(const Duration(hours: 3)).toIso8601String(),
      'imageUrl': 'wheat_rust_sample',
      'shriramProductId': 'prod_shriram_suraksha',
      'shriramProductName': 'Shriram Suraksha (Hexaconazole 5% SC)',
      'dosagePerAcreEn': '400 ml in 200 Liters of water per 1 Acre (Foliar spray)',
      'dosagePerAcreHi': '400 मिली 200 लीटर पानी में मिलाकर प्रति 1 एकड़',
      'matchedProduct': {
        'id': 'prod_shriram_suraksha',
        'nameEn': 'Shriram Suraksha (Hexaconazole 5% SC)',
        'nameHi': 'श्रीराम सुरक्षा (हेक्साकोनाजोल 5% एससी)',
        'category': 'pesticide',
        'mrp': 620.0,
        'subsidizedPrice': 490.0,
        'unitEn': '500 ml Bottle',
        'unitHi': '500 मिली बोतल',
        'inStockCount': 75,
        'descriptionEn': 'Broad spectrum systemic fungicide for rust and powdery mildew.',
        'descriptionHi': 'रतुआ और झुलसा रोगों की रोकथाम हेतु प्रभावी फफूंदनाशी।',
        'isSubsidized': true,
      },
    },
    {
      'id': 'scan_102',
      'cropNameEn': 'Potato Leaf (Solanum tuberosum)',
      'cropNameHi': 'आलू की पत्ती (Potato)',
      'diseaseNameEn': 'Late Blight (Phytophthora infestans)',
      'diseaseNameHi': 'पछेती झुलसा रोग (Late Blight)',
      'confidenceScore': 0.94,
      'isHealthy': false,
      'symptomsEn': 'Dark water-soaked necrotic patches with white fuzzy fungal spores under humid morning mist.',
      'symptomsHi': 'पत्तियों पर गीले गहरे भूरे धब्बे तथा पत्ती के नीचे सफेद फफूंद का जाल।',
      'chemicalRemedyEn': 'Shriram Polyta (Azoxystrobin + Difenoconazole SC): Spray @ 200 ml in 200L water per 1 Acre.',
      'chemicalRemedyHi': 'श्रीराम पॉलिता (एजोक्सिस्ट्रोबिन + डिफेनोकोनाजोल): 200 मिली 200 लीटर पानी में प्रति 1 एकड़।',
      'organicRemedyEn': 'Trichoderma viride bio-fungicide @ 1 kg in 100 kg compost per Acre.',
      'organicRemedyHi': '1 कि.ग्रा. ट्राइकोडर्मा विरिडी 100 कि.ग्रा. सड़ी गोबर खाद में मिलाकर डालें।',
      'preventionEn': 'Crop rotation, avoid overhead irrigation, ensure good field drainage.',
      'preventionHi': 'फसल चक्र अपनाएं एवं खेत में जल निकासी की समुचित व्यवस्था रखें।',
      'scanDate': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      'imageUrl': 'potato_blight_sample',
      'shriramProductId': 'prod_shriram_polyta',
      'shriramProductName': 'Shriram Polyta (Azoxystrobin + Difenoconazole SC)',
      'dosagePerAcreEn': '200 ml in 200 Liters of water per 1 Acre',
      'dosagePerAcreHi': '200 मिली 200 लीटर पानी में मिलाकर प्रति 1 एकड़',
      'matchedProduct': {
        'id': 'prod_shriram_polyta',
        'nameEn': 'Shriram Polyta (Azoxystrobin + Difenoconazole SC)',
        'nameHi': 'श्रीराम पॉलिता (एजोक्सिस्ट्रोबिन + डिफेनोकोनाजोल)',
        'category': 'pesticide',
        'mrp': 1450.0,
        'subsidizedPrice': 1250.0,
        'unitEn': '250 ml Bottle',
        'unitHi': '250 मिली बोतल',
        'inStockCount': 0, // OUT OF STOCK
        'descriptionEn': 'Advanced systemic fungicide with translaminar movement.',
        'descriptionHi': 'आलू झुलसा रोग पर त्वरित असरदार उन्नत फफूंदनाशक।',
        'isSubsidized': true,
      },
    },
    {
      'id': 'scan_103',
      'cropNameEn': 'Paddy Leaf (Oryza sativa)',
      'cropNameHi': 'धान की पत्ती (Paddy / Rice)',
      'diseaseNameEn': 'Healthy Vigorous Foliage',
      'diseaseNameHi': 'स्वस्थ एवं रोगमुक्त धान पत्ती',
      'confidenceScore': 0.98,
      'isHealthy': true,
      'symptomsEn': 'Optimal chlorophyll index with healthy cellular vigor and no active fungal spot.',
      'symptomsHi': 'पत्ती का रंग गहरा हरा व चमकदार है, कोई रोग के लक्षण नहीं मिले।',
      'chemicalRemedyEn': 'Apply Shriram Energy (19:19:19 100% Water Soluble NPK) @ 1.0 kg/Acre as foliar tonic.',
      'chemicalRemedyHi': 'कल्लों की वृद्धि हेतु श्रीराम एनर्जी (19:19:19 एनपीके) 1 किग्रा प्रति एकड़ छिड़कें।',
      'organicRemedyEn': 'Continue regular Jeevamrit / Panchagavya application for soil vigor.',
      'organicRemedyHi': 'मिट्टी की उर्वरता हेतु जीवामृत या पंचगव्य का नियमित प्रयोग जारी रखें।',
      'preventionEn': 'Maintain balanced water table and scout weekly for stem borers.',
      'preventionHi': 'खेत में पानी का उचित स्तर बनाए रखें।',
      'scanDate': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
      'imageUrl': 'healthy_paddy_sample',
      'shriramProductId': 'prod_shriram_energy',
      'shriramProductName': 'Shriram Energy (19:19:19 100% Water Soluble NPK)',
      'dosagePerAcreEn': '1.0 kg in 200 Liters of water per 1 Acre (Foliar spray)',
      'dosagePerAcreHi': '1.0 कि.ग्रा. 200 लीटर पानी में मिलाकर प्रति 1 एकड़',
      'matchedProduct': {
        'id': 'prod_shriram_energy',
        'nameEn': 'Shriram Energy (19:19:19 100% Water Soluble NPK)',
        'nameHi': 'श्रीराम एनर्जी (19:19:19 पूर्ण घुलनशील एनपीके)',
        'category': 'fertilizer',
        'mrp': 350.0,
        'subsidizedPrice': 280.0,
        'unitEn': '1 kg Pack',
        'unitHi': '1 कि.ग्रा. पैकेट',
        'inStockCount': 210,
        'descriptionEn': 'Complete 100% water soluble plant nutrient tonic.',
        'descriptionHi': 'फसलों के समग्र विकास हेतु 100% घुलनशील खाद।',
        'isSubsidized': true,
      },
    },
  ];

  // Seed Shriram Fertilizers & Chemicals Product Inventory
  static final List<Map<String, dynamic>> initialProducts = [
    {
      'id': 'prod_shriram_urea',
      'nameEn': 'Shriram Neem Coated Urea (46% N)',
      'nameHi': 'श्रीराम नीम लेपित यूरिया (46% नाइट्रोजन)',
      'category': 'fertilizer',
      'mrp': 285.0,
      'subsidizedPrice': 266.50,
      'unitEn': '50 kg Bag',
      'unitHi': '50 कि.ग्रा. बोरी',
      'inStockCount': 850,
      'descriptionEn': 'High efficiency slow-release nitrogen from Shriram Fertilizers & Chemicals.',
      'descriptionHi': 'श्रीराम फर्टिलाइजर्स का उच्च गुणवत्ता वाला नीम लेपित यूरिया।',
      'composition': 'Total Nitrogen (N): 46.0% Minimum',
      'dosageEn': '45-50 kg per 1 Acre as split top dressing.',
      'dosageHi': '45-50 कि.ग्रा. प्रति 1 एकड़ विभाजित मात्रा में।',
      'isSubsidized': true,
    },
    {
      'id': 'prod_shriram_dap',
      'nameEn': 'Shriram DAP (18:46:0 Di-Ammonium Phosphate)',
      'nameHi': 'श्रीराम डीएपी 18:46:0 (डाई अमोनियम फॉस्फेट)',
      'category': 'fertilizer',
      'mrp': 1550.0,
      'subsidizedPrice': 1350.00,
      'unitEn': '50 kg Bag',
      'unitHi': '50 कि.ग्रा. बोरी',
      'inStockCount': 420,
      'descriptionEn': 'High purity phosphorus for robust early root system and seedling anchorage.',
      'descriptionHi': 'जड़ विकास व कल्ले फूटने के लिए आवश्यक श्रीराम प्रमाणित डीएपी।',
      'composition': 'Nitrogen: 18.0%, Phosphorus (P2O5): 46.0%',
      'dosageEn': '50 kg per 1 Acre as basal application at sowing.',
      'dosageHi': 'बुवाई के समय 50 कि.ग्रा. प्रति 1 एकड़ बेसल डोज में।',
      'isSubsidized': true,
    },
    {
      'id': 'prod_shriram_ziva',
      'nameEn': 'Shriram Ziva (Mycorrhizal Bio-Fertilizer & Root Energizer)',
      'nameHi': 'श्रीराम जीवा (माइकोराइजा बायो-फर्टिलाइजर)',
      'category': 'fertilizer',
      'mrp': 550.0,
      'subsidizedPrice': 450.00,
      'unitEn': '4 kg Pack',
      'unitHi': '4 कि.ग्रा. पैकेट',
      'inStockCount': 140,
      'descriptionEn': 'Specialized mycorrhizal bio-fertilizer developed by Shriram to multiply root surface area by 300%.',
      'descriptionHi': 'जड़ों के जाल को 3 गुना बढ़ाकर मिट्टी से फास्फोरस व सूक्ष्म पोषक तत्वों का अवशोषण कराता है।',
      'composition': 'Endo & Ecto Mycorrhizal Spores (1200 IP/gm)',
      'dosageEn': '4 kg per 1 Acre mixed with soil or Shriram Urea at tillering.',
      'dosageHi': '4 कि.ग्रा. प्रति 1 एकड़ (यूरिया या मिट्टी में मिलाकर कल्ले फूटते समय)।',
      'isSubsidized': true,
    },
    {
      'id': 'prod_shriram_energy',
      'nameEn': 'Shriram Energy (19:19:19 100% Water Soluble NPK)',
      'nameHi': 'श्रीराम एनर्जी (19:19:19 पूर्ण घुलनशील एनपीके)',
      'category': 'fertilizer',
      'mrp': 350.0,
      'subsidizedPrice': 280.00,
      'unitEn': '1 kg Pack',
      'unitHi': '1 कि.ग्रा. पैकेट',
      'inStockCount': 210,
      'descriptionEn': 'Premium 100% water soluble spray grade NPK for instant crop vitality and grain luster.',
      'descriptionHi': 'पर्णीय छिड़काव हेतु पूर्ण घुलनशील एनपीके टॉनिक जो फसल में तुरंत चमक और हरियाली लाता है।',
      'composition': 'N: 19%, P2O5: 19%, K2O: 19% + Zn, Fe, B',
      'dosageEn': '1.0 kg in 200 Liters of water per 1 Acre (Foliar spray).',
      'dosageHi': '1.0 कि.ग्रा. 200 लीटर पानी में मिलाकर प्रति 1 एकड़ छिड़कें।',
      'isSubsidized': true,
    },
    {
      'id': 'prod_shriram_suraksha',
      'nameEn': 'Shriram Suraksha (Hexaconazole 5% SC Fungicide)',
      'nameHi': 'श्रीराम सुरक्षा (हेक्साकोनाजोल 5% एससी फफूंदनाशक)',
      'category': 'pesticide',
      'mrp': 620.0,
      'subsidizedPrice': 490.00,
      'unitEn': '500 ml Bottle',
      'unitHi': '500 मिली बोतल',
      'inStockCount': 75,
      'descriptionEn': 'Broad spectrum systemic fungicide for rust, sheath blight, and powdery mildew control.',
      'descriptionHi': 'गेहूं में पीला रतुआ और धान में शीथ ब्लाइट का संपूर्ण समाधान।',
      'composition': 'Hexaconazole 5% SC (Suspension Concentrate)',
      'dosageEn': '400 ml in 200 Liters of water per 1 Acre.',
      'dosageHi': '400 मिली 200 लीटर पानी में मिलाकर प्रति 1 एकड़।',
      'isSubsidized': true,
    },
    {
      'id': 'prod_shriram_polyta',
      'nameEn': 'Shriram Polyta (Azoxystrobin 18.2% + Difenoconazole 11.4% SC)',
      'nameHi': 'श्रीराम पॉलिता (एजोक्सिस्ट्रोबिन + डिफेनोकोनाजोल)',
      'category': 'pesticide',
      'mrp': 1450.0,
      'subsidizedPrice': 1250.00,
      'unitEn': '250 ml Bottle',
      'unitHi': '250 मिली बोतल',
      'inStockCount': 0,
      'descriptionEn': 'World-class dual systemic fungicide for complex blight and anthracnose infections.',
      'descriptionHi': 'आलू पछेती झुलसा और सब्जियों में फफूंद रोगों पर त्वरित असरदार।',
      'composition': 'Azoxystrobin 18.2% + Difenoconazole 11.4% SC',
      'dosageEn': '200 ml in 200 Liters of water per 1 Acre.',
      'dosageHi': '200 मिली 200 लीटर पानी में मिलाकर प्रति 1 एकड़।',
      'isSubsidized': true,
    },
    {
      'id': 'prod_shriram_mahun',
      'nameEn': 'Shriram Mahun Nashak (Imidacloprid 17.8% SL)',
      'nameHi': 'श्रीराम माहू नाशक (इमिडाक्लोप्रिड 17.8% एसएल)',
      'category': 'pesticide',
      'mrp': 410.0,
      'subsidizedPrice': 320.00,
      'unitEn': '250 ml Bottle',
      'unitHi': '250 मिली बोतल',
      'inStockCount': 120,
      'descriptionEn': 'Systemic insecticide protecting mustard, cotton, and vegetables against sap-sucking aphids and jassids.',
      'descriptionHi': 'सरसों के माहू (चेपा कीट) और रस चूसक कीटों का संपूर्ण खात्मा।',
      'composition': 'Imidacloprid 17.8% SL',
      'dosageEn': '100 ml in 150-200 Liters of water per 1 Acre.',
      'dosageHi': '100 मिली 150-200 लीटर पानी में मिलाकर प्रति 1 एकड़।',
      'isSubsidized': true,
    },
    {
      'id': 'prod_shriram_kranti',
      'nameEn': 'Shriram Kranti Zinc (Zinc Sulphate 33% Monohydrate)',
      'nameHi': 'श्रीराम क्रांति जिंक (33% जिंक + 15% सल्फर)',
      'category': 'fertilizer',
      'mrp': 480.0,
      'subsidizedPrice': 390.00,
      'unitEn': '5 kg Pack',
      'unitHi': '5 कि.ग्रा. पैकेट',
      'inStockCount': 180,
      'descriptionEn': 'High-potency micro-nutrient correcting Khaira in paddy and interveinal chlorosis in wheat.',
      'descriptionHi': 'धान में खैरा रोग और गेहूं में पीलापन दूर करने वाला श्रीराम क्रांति जिंक।',
      'composition': 'Zinc (Zn): 33%, Sulphur (S): 15%',
      'dosageEn': '5 kg per 1 Acre soil application at field preparation.',
      'dosageHi': '5 कि.ग्रा. प्रति 1 एकड़ बुवाई से पूर्व मिट्टी में डालें।',
      'isSubsidized': true,
    },
  ];

  // Seed Notices
  static final List<Map<String, dynamic>> initialNotices = [
    {
      'id': 'notice_1',
      'titleEn': 'Shriram Urea & DAP Stock Allocation at Jethwara Center',
      'titleHi': 'जेठवारा केंद्र पर श्रीराम यूरिया व डीएपी खाद आवंटन सूचना',
      'contentEn': 'Fresh railway rake of 1,200 bags Shriram Neem Coated Urea & Shriram DAP has arrived at Sonpur Sewa Samiti warehouse near UP Gramin Bank, Jethwara. Registered farmers can collect with Aadhaar/KCC.',
      'contentHi': 'सोनपुर सेवा समिति (यूपी ग्रामीण बैंक के पास, जेठवारा, प्रतापगढ़) पर श्रीराम यूरिया और डीएपी की 1,200 बोरियां उपलब्ध हैं। किसान भाई आधार/KCC कार्ड दिखाकर प्राप्त करें।',
      'category': 'subsidy',
      'publishedDate': DateTime.now().subtract(const Duration(hours: 18)).toIso8601String(),
      'author': 'Sonpur Sewa Samiti (Jethwara)',
      'isUrgent': true,
    },
  ];

  // Seed Farmer Queries
  static final List<Map<String, dynamic>> initialQueries = [
    {
      'id': 'query_01',
      'farmerName': 'Ramvilas Yadav',
      'village': 'Jethwara, Pratapgarh',
      'cropName': 'Wheat (HD-2967)',
      'questionEn': 'My wheat leaves are turning pale yellow in patches after the first irrigation. What Shriram product should I apply?',
      'questionHi': 'पहली सिंचाई के बाद गेहूं की पत्तियों में हल्के पीले रंग के धब्बे दिख रहे हैं। कौन सी श्रीराम खाद डालनी चाहिए?',
      'responseEn': 'Apply Shriram Kranti Zinc (5 kg/Acre) along with 45 kg Shriram Neem Coated Urea and Shriram Ziva root energizer (4 kg/Acre) for instant deep greening and root growth.',
      'responseHi': 'शीघ्र सुधार हेतु 45 कि.ग्रा. श्रीराम यूरिया के साथ 5 कि.ग्रा. श्रीराम क्रांति जिंक व 4 कि.ग्रा. श्रीराम जीवा मिलाकर खेत में डालें।',
      'status': 'resolved',
      'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      'expertName': 'Dr. S. K. Mishra (Senior Agronomist)',
    },
  ];
}
